HULK_keywords = {
    "PI": "Constant",
    "E": "Constant",
    "print": "print",
    "sqrt": "sqrt",
    "new": "new",
    "inherits": "inherits",
    "cos": "cos",
    "sin": "sin",
    "exp": "exp",
    "true": "Bool",
    "false": "Bool",
    "while": "while",
    "for": "for",
    "range": "range",
    "log": "log",
    "rand": "rand",
    "function": "function",
    "let": "let",
    "in": "in",
    "if": "if",
    "else": "else",
    "type": "type",
    "self": "self",
    "protocol": "protocol",
    "extends": "extends",
}